# serverless.yml
ganniRepeatWebsite:
  component: "@sls-next/serverless-component@3.6.0" # it is recommended you pin the latest stable version of serverless-next.js
  inputs:
    domain: ["dev2074", "ganni-repeat.com"]
    useServerlessTraceTarget: true
    build:
      env:
        NEXT_PUBLIC_API_URL: https://api-dev2074.ganni-repeat.com
        NEXT_PUBLIC_MEDIA_URL: https://media-dev2074.ganni-repeat.com
        NEXT_PUBLIC_MAIN_URL: https://dev2074.ganni-repeat.com
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: pk_test_51KW0ZFJiMSsjx6P4bqT1yF4EUMX7sLDMmZy0ZKildgGp0dNy4406wP25fXjTN2Zkp8D34IIwbi5diVyGygdVF3jK007yoDUzos
        NEXT_PUBLIC_CLIENT_KEY: ck_4b0b2654d6d590a809dba5d777e44e
        NEXT_PUBLIC_COMING_SOON: false
        NEXT_PUBLIC_CONTENT_AUTH: false
        NEXT_PUBLIC_GTM_ID: GTM-TM4JXF2
        NEXT_PUBLIC_ALGOLIA_ID: NI0XCUIASE
        NEXT_PUBLIC_ALGOLIA_KEY: 6d05a4011660b3f4998bbfb8c0b3c27b
        NEXT_PUBLIC_MEDIA_BUCKET_NAME: media-dev2074.ganni-repeat.com
    cloudfront:
      # if you want to use an existing cloudfront distribution, provide it here
      #distributionId: XYZEXAMPLE #optional
      # this is the default cache behaviour of the cloudfront distribution
      # the origin-request edge lambda associated to this cache behaviour does the pages server side rendering
      defaults:
        forward:
          headers:
            [
              CloudFront-Is-Desktop-Viewer,
              CloudFront-Is-Mobile-Viewer,
              CloudFront-Is-Tablet-Viewer,
            ]
      # this is the cache behaviour for next.js api pages
      # api:
      #   minTTL: 10
      #   maxTTL: 10
      #   defaultTTL: 10
      # # you can set other cache behaviours like "defaults" above that can handle server side rendering
      # # but more specific for a subset of your next.js pages
      # /blog/*:
      #   minTTL: 1000
      #   maxTTL: 1000
      #   defaultTTL: 1000
      #   forward:
      #     cookies: "all"
      #     queryString: false
      # /about:
      #   minTTL: 3000
      #   maxTTL: 3000
      #   defaultTTL: 3000
      # you can add custom origins to the cloudfront distribution
      # origins:
      #   - url: /static
      #     pathPatterns:
      #       /wp-content/*:
      #         minTTL: 10
      #         maxTTL: 10
      #         defaultTTL: 10
      #   - url: https://old-static.com
      #     pathPatterns:
      #       /old-static/*:
      #         minTTL: 10
      #         maxTTL: 10
      #         defaultTTL: 10
      #   - url: http://old-api.com
      #     protocolPolicy: http-only
      #     pathPatterns:
      #       /old-api/*:
      #         minTTL: 10
      #         maxTTL: 10
      #         defaultTTL: 10
      aliases: ["dev2074.ganni-repeat.com"]
      # priceClass: "PriceClass_100"
      # You can add custom error responses
      # errorPages:
      #   - code: 503
      #     path: "/503.html"
      #     minTTL: 5 # optional, minimum ttl the error is cached (default 10)
      #     responseCode: 500 # optional, alters the response code
      # comment: "a comment" # optional, describes your distribution
      # webACLId: "arn:aws:wafv2:us-east-1:123456789012:global/webacl/ExampleWebACL/473e64fd-f30b-4765-81a0-62ad96dd167a" # ARN of WAF
      # restrictions:
      #   geoRestriction:
      #     restrictionType: "blacklist" # valid values are whitelist/blacklist/none. Set to "none" and omit items to disable restrictions
      #     items: ["AA"] # ISO 3166 alpha-2 country codes

      certificate:
        cloudFrontDefaultCertificate: false # specify false and one of IAM/ACM certificates, or specify true and omit IAM/ACM inputs for default certificate
        acmCertificateArn: "arn:aws:acm:us-east-1:850126326796:certificate/b8058a7c-016f-4e5e-bd8a-ed3a61e27e8a"
        # iamCertificateId: "iam-certificate-id" # specify either ACM or IAM certificate, not both
        sslSupportMethod: "sni-only" # can be omitted, defaults to "sni-only"
        minimumProtocolVersion: "TLSv1.2_2019" # can be omitted, defaults to "TLSv1.2_2019"
      # originAccessIdentityId: XYZEXAMPLE #optional
      paths: ["/*"] # which paths should be invalidated on deploy, default matches everything, empty array skips invalidation completely
      waitBeforeInvalidate: true # by default true, it waits for the CloudFront distribution to have completed before invalidating, to avoid possibly caching old page
